name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  create-deployment-artifacts:
    name: Create Deployment Artifacts
    run-on: ubuntu-latest
    steps:
      - user: actions/checkout@v2

      - name: Compile CSS and Javarscript
        run: |
          npm install
          npm run prod
